version: '2'
volumes:
  workshop-mysql-data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: workshop-mysql
    volumes:
      - workshop-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=workshop
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  app:
    image: webdevops/php-apache-dev:7.4
    container_name: workshop-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_MEMORY_LIMIT=-1
    links:
      - mysql


